# İmage olarak kullanacağımız temel CS 1.6 sunucusu imajını alın
FROM cm2network/steamcmd:root

# Gerekli bağımlılıkları yükleyin
RUN apt-get update && \
    apt-get install -y --no-install-recommends lib32gcc1 ca-certificates

USER container
ENV  USER container
ENV HOME /home/container


WORKDIR /home/container
COPY ./entrypoint.sh /entrypoint.sh


CMD ["/bin/ash", "/entrypoint.sh"]
